# frozen_string_literal: true

source 'http://rubygems.org'

gem 'thin', '1.7.1'
gem 'rack', '2.0.3'
gem 'rack-cors', '1.0.2'
gem 'whenever', '0.10.0'
gem 'jwt', '2.1.0'
gem "roo", "2.7.1"
gem 'rest-client', '2.0.2'

group :localdocker, :development, :test do
  gem 'pry'
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
  gem 'database_cleaner', '~> 1.6'
  gem 'simplecov'
end
